{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# print P(x|yes) and P(x|no) for each attribute x\n",
    "# P(x|yes) = count of x in yes / count of yes \n",
    "# probability of x given yes\n",
    "# probability of x given no\n",
    "# posteriotr probability\n",
    "# also do normalization\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "data = pd.read_csv('play_tennis.csv')\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# def calculate_prior(data, target):\n",
    "#     classes = data[target].unique()\n",
    "#     priors = {}\n",
    "#     for cls in classes:\n",
    "#         priors[cls] = len(data[data[target] == cls]) / len(data)\n",
    "#     return priors\n",
    "\n",
    "# def calculate_likelihood(data, feature, target):\n",
    "#     likelihoods = {}\n",
    "#     classes = data[target].unique()\n",
    "#     for cls in classes:\n",
    "#         class_data = data[data[target] == cls]\n",
    "#         feature_values = class_data[feature].unique()\n",
    "#         likelihoods[cls] = {}\n",
    "#         for value in feature_values:\n",
    "#             likelihoods[cls][value] = len(class_data[class_data[feature] == value]) / len(class_data)\n",
    "#     return likelihoods\n",
    "\n",
    "# # Calculate posterior probabilities\n",
    "# def calculate_posterior(priors, likelihoods, sample):\n",
    "#     posteriors = {}\n",
    "#     for cls in priors:\n",
    "#         posteriors[cls] = priors[cls]\n",
    "#         for feature in sample:\n",
    "#             if sample[feature] in likelihoods[cls]:\n",
    "#                 posteriors[cls] *= likelihoods[cls][sample[feature]]\n",
    "#             else:\n",
    "#                 posteriors[cls] *= 0\n",
    "#     return posteriors\n",
    "\n",
    "# # Predict the class for a new sample\n",
    "# def predict(data, sample, target):\n",
    "#     priors = calculate_prior(data, target)\n",
    "#     likelihoods = {}\n",
    "#     for feature in data.columns:\n",
    "#         if feature != target:\n",
    "#             likelihoods[feature] = calculate_likelihood(data, feature, target)\n",
    "#     posteriors = calculate_posterior(priors, likelihoods, sample)\n",
    "#     return max(posteriors, key=posteriors.get)\n",
    "\n",
    "# # Example usage\n",
    "# sample = {'Outlook': 'Sunny', 'Temperature': 'Hot', 'Humidity': 'High', 'Wind': 'Weak'}\n",
    "# prediction = predict(data, sample, 'PlayTennis')\n",
    "# print(f'The prediction for the sample {sample} is: {prediction}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Prior Probabilities (P(class)):\n",
      "{'Yes': 0.6, 'No': 0.4}\n",
      "\n",
      "Conditional Probabilities (P(x | class)):\n",
      "{'Outlook': {('Sunny', 'No'): 0.75, ('Sunny', 'Yes'): 0.16666666666666666, ('Overcast', 'No'): 0.0, ('Overcast', 'Yes'): 0.3333333333333333, ('Rain', 'No'): 0.25, ('Rain', 'Yes'): 0.5}, 'Temperature': {('Hot', 'No'): 0.5, ('Hot', 'Yes'): 0.16666666666666666, ('Mild', 'No'): 0.25, ('Mild', 'Yes'): 0.3333333333333333, ('Cool', 'No'): 0.25, ('Cool', 'Yes'): 0.5}, 'Humidity': {('High', 'No'): 0.75, ('High', 'Yes'): 0.3333333333333333, ('Normal', 'No'): 0.25, ('Normal', 'Yes'): 0.6666666666666666}, 'Wind': {('Weak', 'No'): 0.5, ('Weak', 'Yes'): 0.8333333333333334, ('Strong', 'No'): 0.5, ('Strong', 'Yes'): 0.16666666666666666}}\n",
      "\n",
      "Predicting for row 0: {'Outlook': 'Sunny', 'Temperature': 'Hot', 'Humidity': 'High', 'Wind': 'Weak'}\n",
      "  - Initial Posterior (P(Yes)): 0.6\n",
      "    P(Outlook = Sunny | Yes) = 0.16666666666666666\n",
      "    Updated Posterior (P(Yes | X)): 0.09999999999999999\n",
      "    P(Temperature = Hot | Yes) = 0.16666666666666666\n",
      "    Updated Posterior (P(Yes | X)): 0.016666666666666663\n",
      "    P(Humidity = High | Yes) = 0.3333333333333333\n",
      "    Updated Posterior (P(Yes | X)): 0.005555555555555554\n",
      "    P(Wind = Weak | Yes) = 0.8333333333333334\n",
      "    Updated Posterior (P(Yes | X)): 0.0046296296296296285\n",
      "  - Final Posterior for class Yes: 0.0046296296296296285\n",
      "  - Initial Posterior (P(No)): 0.4\n",
      "    P(Outlook = Sunny | No) = 0.75\n",
      "    Updated Posterior (P(No | X)): 0.30000000000000004\n",
      "    P(Temperature = Hot | No) = 0.5\n",
      "    Updated Posterior (P(No | X)): 0.15000000000000002\n",
      "    P(Humidity = High | No) = 0.75\n",
      "    Updated Posterior (P(No | X)): 0.11250000000000002\n",
      "    P(Wind = Weak | No) = 0.5\n",
      "    Updated Posterior (P(No | X)): 0.05625000000000001\n",
      "  - Final Posterior for class No: 0.05625000000000001\n",
      "  - Total Posterior: 0.06087962962962964\n",
      "  - Normalized Posterior: {'Yes': 0.07604562737642583, 'No': 0.9239543726235742}\n",
      "  - Predicted Class: No\n",
      "========================================\n",
      "Final Prediction for new data: ['No']\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "class NaiveBayesClassifier:\n",
    "    def __init__(self):\n",
    "        self.class_probs = {}\n",
    "        self.cond_probs = {}\n",
    "\n",
    "    def fit(self, X, y):\n",
    "        self.class_probs = self.calculate_class_probs(y)\n",
    "        print(\"Prior Probabilities (P(class)):\")\n",
    "        print(self.class_probs)\n",
    "        print()\n",
    "\n",
    "        self.cond_probs = self.calculate_conditional_probs(X, y)\n",
    "        print(\"Conditional Probabilities (P(x | class)):\")\n",
    "        print(self.cond_probs)\n",
    "        print()\n",
    "\n",
    "    def calculate_class_probs(self, y):\n",
    "        class_counts = y.value_counts()\n",
    "        total_count = len(y)\n",
    "        class_probs = class_counts / total_count\n",
    "        return class_probs.to_dict()\n",
    "\n",
    "    def calculate_conditional_probs(self, X, y):\n",
    "        cond_probs = {}\n",
    "        for column in X.columns:\n",
    "            cond_probs[column] = {}\n",
    "            for value in X[column].unique():\n",
    "                for class_value in y.unique():\n",
    "                    count_x_given_class = len(X[(X[column] == value) & (y == class_value)])\n",
    "                    count_class = len(y[y == class_value])\n",
    "                    prob = count_x_given_class / count_class\n",
    "                    cond_probs[column][(value, class_value)] = prob\n",
    "        return cond_probs\n",
    "\n",
    "    def predict(self, X):\n",
    "        predictions = []\n",
    "        for index, row in X.iterrows():\n",
    "            posteriors = {}\n",
    "            print(f\"Predicting for row {index}: {row.to_dict()}\")\n",
    "            for class_value, class_prob in self.class_probs.items():\n",
    "                posterior = class_prob\n",
    "                print(f\"  - Initial Posterior (P({class_value})): {posterior}\")\n",
    "\n",
    "                for column, value in row.items():\n",
    "                    cond_prob = self.cond_probs[column].get((value, class_value), 0)\n",
    "                    posterior *= cond_prob\n",
    "                    print(f\"    P({column} = {value} | {class_value}) = {cond_prob}\")\n",
    "                    print(f\"    Updated Posterior (P({class_value} | X)): {posterior}\")\n",
    "\n",
    "                posteriors[class_value] = posterior\n",
    "                print(f\"  - Final Posterior for class {class_value}: {posterior}\")\n",
    "            \n",
    "            total_posterior = sum(posteriors.values())\n",
    "            print(f\"  - Total Posterior: {total_posterior}\")\n",
    "            if total_posterior > 0:\n",
    "                posteriors = {k: v / total_posterior for k, v in posteriors.items()}\n",
    "            print(f\"  - Normalized Posterior: {posteriors}\")\n",
    "            \n",
    "            predictions.append(max(posteriors, key=posteriors.get))  # Choose the class with the highest posterior\n",
    "            print(f\"  - Predicted Class: {predictions[-1]}\")\n",
    "            print(\"=\" * 40)\n",
    "\n",
    "        return predictions\n",
    "\n",
    "\n",
    "# Example dataset\n",
    "data = {\n",
    "    'Outlook': ['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 'Sunny', 'Sunny', 'Rain'],\n",
    "    'Temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild'],\n",
    "    'Humidity': ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'Normal'],\n",
    "    'Wind': ['Weak', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Weak', 'Weak'],\n",
    "    'PlayTennis': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes']\n",
    "}\n",
    "\n",
    "# Convert the data to DataFrame\n",
    "df = pd.DataFrame(data)\n",
    "\n",
    "# Feature columns and target column\n",
    "X = df.drop('PlayTennis', axis=1)\n",
    "y = df['PlayTennis']\n",
    "\n",
    "# Initialize and train the Naive Bayes classifier\n",
    "nb_classifier = NaiveBayesClassifier()\n",
    "nb_classifier.fit(X, y)\n",
    "\n",
    "# Sample prediction: Predict whether tennis is played based on some new data\n",
    "new_data = pd.DataFrame({\n",
    "    'Outlook': ['Sunny'],\n",
    "    'Temperature': ['Hot'],\n",
    "    'Humidity': ['High'],\n",
    "    'Wind': ['Weak']\n",
    "})\n",
    "\n",
    "predictions = nb_classifier.predict(new_data)\n",
    "print(\"Final Prediction for new data:\", predictions)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
